flights: 
  extract: true
  name: opt_4cfs_window_trial
  data:

    # 4 cfs window opt trial: 
    - [4cfs_window/cf2/opt/trial/cf2_1_02, 4cfs_window/cf3/opt/trial/cf3_1_02, 4cfs_window/cf7/opt/trial/cf7_1_02, 4cfs_window/cf9/opt/trial/cf9_1_02]
    - [4cfs_window/cf2/opt/trial/cf2_1_03, 4cfs_window/cf3/opt/trial/cf3_1_03, 4cfs_window/cf7/opt/trial/cf7_1_03, 4cfs_window/cf9/opt/trial/cf9_1_03]


    # 3 cfs window opt: 
    # - [3cfs_window/cf2/opt/cf2_1_00, 3cfs_window/cf3/opt/cf3_1_00, 3cfs_window/cf7/opt/cf7_1_00]
    # - [3cfs_window/cf2/opt/cf2_1_01, 3cfs_window/cf3/opt/cf3_1_01, 3cfs_window/cf7/opt/cf7_1_01]
    # - [3cfs_window/cf2/opt/cf2_1_02, 3cfs_window/cf3/opt/cf3_1_02, 3cfs_window/cf7/opt/cf7_1_02]
    # - [3cfs_window/cf2/opt/cf2_1_03, 3cfs_window/cf3/opt/cf3_1_03, 3cfs_window/cf7/opt/cf7_1_03]
    # - [3cfs_window/cf2/opt/cf2_1_04, 3cfs_window/cf3/opt/cf3_1_04, 3cfs_window/cf7/opt/cf7_1_04]
    # - [3cfs_window/cf2/opt/cf2_1_05, 3cfs_window/cf3/opt/cf3_1_05, 3cfs_window/cf7/opt/cf7_1_05]
    # - [3cfs_window/cf2/opt/cf2_1_06, 3cfs_window/cf3/opt/cf3_1_06, 3cfs_window/cf7/opt/cf7_1_06]
    # - [3cfs_window/cf2/opt/cf2_1_07, 3cfs_window/cf3/opt/cf3_1_07, 3cfs_window/cf7/opt/cf7_1_07]
    # - [3cfs_window/cf2/opt/cf2_1_08, 3cfs_window/cf3/opt/cf3_1_08, 3cfs_window/cf7/opt/cf7_1_08]
    # - [3cfs_window/cf2/opt/cf2_1_09, 3cfs_window/cf3/opt/cf3_1_09, 3cfs_window/cf7/opt/cf7_1_09]

    # 3 cfs window geom: 
    # - [3cfs_window/cf2/geom/cf2_1_01, 3cfs_window/cf3/geom/cf3_1_01 ,3cfs_window/cf7/geom/cf7_1_01]
    # - [3cfs_window/cf2/geom/cf2_1_03, 3cfs_window/cf3/geom/cf3_1_03 ,3cfs_window/cf7/geom/cf7_1_03]
    # - [3cfs_window/cf2/geom/cf2_1_04, 3cfs_window/cf3/geom/cf3_1_04 ,3cfs_window/cf7/geom/cf7_1_04]
    # - [3cfs_window/cf2/geom/cf2_1_06, 3cfs_window/cf3/geom/cf3_1_06 ,3cfs_window/cf7/geom/cf7_1_06]
    # - [3cfs_window/cf2/geom/cf2_1_08, 3cfs_window/cf3/geom/cf3_1_08 ,3cfs_window/cf7/geom/cf7_1_08]
    # - [3cfs_window/cf2/geom/cf2_1_09, 3cfs_window/cf3/geom/cf3_1_09 ,3cfs_window/cf7/geom/cf7_1_09]

  
    # 2 cfs window geom:
    # - [cf2/geom/cf2_1_00, cf7/geom/cf7_1_00]
    # - [cf2/geom/cf2_1_03, cf7/geom/cf7_1_03]
    # - [cf2/geom/cf2_1_04, cf7/geom/cf7_1_04]
    # - [cf2/geom/cf2_1_05, cf7/geom/cf7_1_05]
    # - [cf2/geom/cf2_1_06, cf7/geom/cf7_1_06]
    # - [cf2/geom/cf2_1_07, cf7/geom/cf7_1_07]
    # - [cf2/geom/cf2_1_08, cf7/geom/cf7_1_08]
    # - [cf2/geom/cf2_1_09, cf7/geom/cf7_1_09]

    # 2 cfs window opt:
    # - [cf2/opt/cf2_1_01, cf7/opt/cf7_1_01]
    # - [cf2/opt/cf2_1_02, cf7/opt/cf7_1_02]
    # - [cf2/opt/cf2_1_03, cf7/opt/cf7_1_03]
    # - [cf2/opt/cf2_1_04, cf7/opt/cf7_1_04]
    # - [cf2/opt/cf2_1_05, cf7/opt/cf7_1_05]
    # - [cf2/opt/cf2_1_06, cf7/opt/cf7_1_06]
    # - [cf2/opt/cf2_1_07, cf7/opt/cf7_1_07]
    # - [cf2/opt/cf2_1_08, cf7/opt/cf7_1_08]
    # - [cf2/opt/cf2_1_09, cf7/opt/cf7_1_09]
    # - [cf2/opt/cf2_1_10, cf7/opt/cf7_1_10]

start_time: 2.0
end_time: 40.0
plot:
  enabled: true
  files:
    # 4 cfs window opt trial: 
    - [4cfs_window/cf2/opt/trial/cf2_1_02, 4cfs_window/cf3/opt/trial/cf3_1_02, 4cfs_window/cf7/opt/trial/cf7_1_02, 4cfs_window/cf9/opt/trial/cf9_1_02]
    - [4cfs_window/cf2/opt/trial/cf2_1_03, 4cfs_window/cf3/opt/trial/cf3_1_03, 4cfs_window/cf7/opt/trial/cf7_1_03, 4cfs_window/cf9/opt/trial/cf9_1_03]
    
    # 3 cfs window opt: 
    # - [3cfs_window/cf2/opt/cf2_1_00, 3cfs_window/cf3/opt/cf3_1_00, 3cfs_window/cf7/opt/cf7_1_00]
    # - [3cfs_window/cf2/opt/cf2_1_01, 3cfs_window/cf3/opt/cf3_1_01, 3cfs_window/cf7/opt/cf7_1_01]
    # - [3cfs_window/cf2/opt/cf2_1_02, 3cfs_window/cf3/opt/cf3_1_02, 3cfs_window/cf7/opt/cf7_1_02]
    # - [3cfs_window/cf2/opt/cf2_1_03, 3cfs_window/cf3/opt/cf3_1_03, 3cfs_window/cf7/opt/cf7_1_03]
    # - [3cfs_window/cf2/opt/cf2_1_04, 3cfs_window/cf3/opt/cf3_1_04, 3cfs_window/cf7/opt/cf7_1_04]
    # - [3cfs_window/cf2/opt/cf2_1_05, 3cfs_window/cf3/opt/cf3_1_05, 3cfs_window/cf7/opt/cf7_1_05]
    # - [3cfs_window/cf2/opt/cf2_1_06, 3cfs_window/cf3/opt/cf3_1_06, 3cfs_window/cf7/opt/cf7_1_06]
    # - [3cfs_window/cf2/opt/cf2_1_07, 3cfs_window/cf3/opt/cf3_1_07, 3cfs_window/cf7/opt/cf7_1_07]
    # - [3cfs_window/cf2/opt/cf2_1_08, 3cfs_window/cf3/opt/cf3_1_08, 3cfs_window/cf7/opt/cf7_1_08]
    # - [3cfs_window/cf2/opt/cf2_1_09, 3cfs_window/cf3/opt/cf3_1_09, 3cfs_window/cf7/opt/cf7_1_09]

    # 3 cfs window geom: 
    # - [3cfs_window/cf2/geom/cf2_1_01, 3cfs_window/cf3/geom/cf3_1_01 ,3cfs_window/cf7/geom/cf7_1_01]
    # - [3cfs_window/cf2/geom/cf2_1_03, 3cfs_window/cf3/geom/cf3_1_03 ,3cfs_window/cf7/geom/cf7_1_03]
    # - [3cfs_window/cf2/geom/cf2_1_04, 3cfs_window/cf3/geom/cf3_1_04 ,3cfs_window/cf7/geom/cf7_1_04]
    # - [3cfs_window/cf2/geom/cf2_1_06, 3cfs_window/cf3/geom/cf3_1_06 ,3cfs_window/cf7/geom/cf7_1_06]
    # - [3cfs_window/cf2/geom/cf2_1_08, 3cfs_window/cf3/geom/cf3_1_08 ,3cfs_window/cf7/geom/cf7_1_08]
    # - [3cfs_window/cf2/geom/cf2_1_09, 3cfs_window/cf3/geom/cf3_1_09 ,3cfs_window/cf7/geom/cf7_1_09]


    # 2 cfs window geom:
    # - [cf2/geom/cf2_1_00, cf7/geom/cf7_1_00]
    # - [cf2/geom/cf2_1_03, cf7/geom/cf7_1_03]
    # - [cf2/geom/cf2_1_04, cf7/geom/cf7_1_04]
    # - [cf2/geom/cf2_1_05, cf7/geom/cf7_1_05]
    # - [cf2/geom/cf2_1_06, cf7/geom/cf7_1_06]
    # - [cf2/geom/cf2_1_07, cf7/geom/cf7_1_07]
    # - [cf2/geom/cf2_1_08, cf7/geom/cf7_1_08]
    # - [cf2/geom/cf2_1_09, cf7/geom/cf7_1_09]

    # 2 cfs window opt:
    # - [cf2/opt/cf2_1_01, cf7/opt/cf7_1_01]
    # - [cf2/opt/cf2_1_02, cf7/opt/cf7_1_02]
    # - [cf2/opt/cf2_1_03, cf7/opt/cf7_1_03]
    # - [cf2/opt/cf2_1_04, cf7/opt/cf7_1_04]
    # - [cf2/opt/cf2_1_05, cf7/opt/cf7_1_05]
    # - [cf2/opt/cf2_1_06, cf7/opt/cf7_1_06]
    # - [cf2/opt/cf2_1_07, cf7/opt/cf7_1_07]
    # - [cf2/opt/cf2_1_08, cf7/opt/cf7_1_08]
    # - [cf2/opt/cf2_1_09, cf7/opt/cf7_1_09]
    # - [cf2/opt/cf2_1_10, cf7/opt/cf7_1_10]


data_to_plot:  
    page1:
      special: true # if this plot needs a special calculation 
      plot_labels: ["x [m]", "y [m]", "z [m]"]
      unit: mm 
      data:
        name1: p0
        data1: [stateEstimateZ.px, stateEstimateZ.py, stateEstimateZ.pz]
        name2: p0d
        data2: [ctrltargetZ.x, ctrltargetZ.y, ctrltargetZ.z]
        timestamp: []
      title: Payload Pose
      num_of_plots: 3

    page2:
      special: false
      plot_labels: ['vx [m/s]', 'vy [m/s]', 'vz [m/s]']
      unit: mm
      data:
        name1: v0
        data1: [stateEstimateZ.pvx, stateEstimateZ.pvy, stateEstimateZ.pvz]
        name2: v0d
        data2: [ctrltargetZ.vx, ctrltargetZ.vy, ctrltargetZ.vz]
      title: Payload Velocity
      num_of_plots: 3

    page3:
      special: true
      plot_labels: ['f1 [g]', 'f2 [g]', 'f3 [g]', 'f4 [g]', 'maxThrust']
      unit: g
      data:
        name1: Thrust
        data1: [powerDist.thrustPart, powerDist.rollPart, powerDist.pitchPart, powerDist.yawPart, powerDist.maxThrust] 
      title: Thrust 
      num_of_plots: 4

    page4:
      special: false
      plot_labels: ['Fdx [N]', 'Fdy [N]', 'Fdz [N]']
      unit: N 
      data:
        name1: Fd
        data1: [ctrlLeeP.Fdx, ctrlLeeP.Fdy, ctrlLeeP.Fdz] 
      title: Desired Payload Force
      num_of_plots: 3


    page5:
      special: false
      plot_labels: ['mux [N]', 'muy [N]', 'muz [N]']
      unit: N 
      data:
        name1: mu
        data1: [ctrlLeeP.desVirtInpx, ctrlLeeP.desVirtInpy, ctrlLeeP.desVirtInpz] 
        name2: mu_ref
        data2: [ctrlLeeP.mu_refx, ctrlLeeP.mu_refy, ctrlLeeP.mu_refz] 
      title: Desired Cable force
      num_of_plots: 3

    page6:
      special: false
      plot_labels: ['qix []', 'qiy []', 'qiz []']
      unit: N 
      data:
        name1: qi
        data1: [ctrlLeeP.qix, ctrlLeeP.qiy, ctrlLeeP.qiz] 
        name2: qdi
        data2: [ctrlLeeP.qdix, ctrlLeeP.qdiy, ctrlLeeP.qdiz] 
      title: Cable Unit Vectors
      num_of_plots: 3

    page7:
      special: false
      plot_labels: ['qidotx [rad/s]', 'qidoty [rad/s]', 'qidotz [rad/s]']
      unit: N 
      data:
        name1: qidot
        data1: [ctrlLeeP.qidotx, ctrlLeeP.qidoty, ctrlLeeP.qidotz] 
        name2: qidref
        data2: [ctrlLeeP.qidrefx, ctrlLeeP.qidrefy, ctrlLeeP.qidrefz] 
      title: Cable Unit Vector Derivative
      num_of_plots: 3
