- name: ex1
  Fd: [0,0,0.1]
  payload:
    model: pointmass
    position: [0,0,0]
    rotation: [1,0,0,0]
    attachementpoints: # in relative coordinates
      - [0,0,0]
  uavs:
    - cable_length: 0.6 # m
      inclination: 20 # 0-180 deg
      azimuth: 0 # 0-360 deg
      safety_radius: 0.15 # m
    - cable_length: 0.9 # m
      inclination: -20 # 0-180 deg
      azimuth: 45 # 0-360 deg
      safety_radius: 0.15 # m