#ifndef WORKSPACE_H
#define WORKSPACE_H

/*
 * This file was autogenerated by OSQP-Python on August 23, 2022 at 17:24:55.
 * 
 * This file contains the prototypes for all the workspace variables needed
 * by OSQP. The actual data is contained inside workspace.c.
 */

#include "types.h"
#include "qdldl_interface.h"

// Data structure prototypes
extern csc Pdata;
extern csc Adata;
extern c_float qdata[2];
extern c_float ldata[3];
extern c_float udata[3];
extern OSQPData data;

// Settings structure prototype
extern OSQPSettings settings;

// Scaling structure prototypes
extern c_float Dscaling[2];
extern c_float Dinvscaling[2];
extern c_float Escaling[3];
extern c_float Einvscaling[3];
extern OSQPScaling scaling;

// Prototypes for linsys_solver structure
extern csc linsys_solver_L;
extern c_float linsys_solver_Dinv[5];
extern c_int linsys_solver_P[5];
extern c_float linsys_solver_bp[5];
extern c_float linsys_solver_sol[5];
extern c_float linsys_solver_rho_inv_vec[3];
extern qdldl_solver linsys_solver;

// Prototypes for solution
extern c_float xsolution[2];
extern c_float ysolution[3];

extern OSQPSolution solution;

// Prototype for info structure
extern OSQPInfo info;

// Prototypes for the workspace
extern c_float work_rho_vec[3];
extern c_float work_rho_inv_vec[3];
extern c_float work_x[2];
extern c_float work_y[3];
extern c_float work_z[3];
extern c_float work_xz_tilde[5];
extern c_float work_x_prev[2];
extern c_float work_z_prev[3];
extern c_float work_Ax[3];
extern c_float work_Px[2];
extern c_float work_Aty[2];
extern c_float work_delta_y[3];
extern c_float work_Atdelta_y[2];
extern c_float work_delta_x[2];
extern c_float work_Pdelta_x[2];
extern c_float work_Adelta_x[3];
extern c_float work_D_temp[2];
extern c_float work_D_temp_A[2];
extern c_float work_E_temp[3];

extern OSQPWorkspace workspace;

#endif // ifndef WORKSPACE_H
