# named list of all robots
robots:
  cf7:
    enabled: true
    uri: radio://0/85/2M/E7E7E7E707
    initial_position: [-1.0, 0.25, 0.0]
    type: cf21 # see robot_types
    # firmware_params:
    #   ring:
    #     solidBlue: 255 # if set to solid color
    #     solidGreen: 0 # if set to solid color
    #     solidRed: 0 # if set to solid color

  cf9:
    enabled: true
    uri: radio://0/85/2M/E7E7E7E709
    initial_position: [-1.0, -0.25, 0.0]
    type: cf21 # see robot_types
    # firmware_params:
      # ring:
      #   solidBlue: 0 # if set to solid color
      #   solidGreen: 0 # if set to solid color
      #   solidRed: 255 # if set to solid color


  payload:
    enabled: true
    initial_position: [-1.0, 0.0, 0.0]
    type: marker    # see robot_types
    id: 255

# Definition of the various robot types
robot_types:
  cf21:
    motion_capture:
      enabled: true
      # only if enabled; see motion_capture.yaml
      marker: default_single_marker  #  default_single_marker
      dynamics: default
    big_quad: false
    battery:
      voltage_warning: 3.8  # V
      voltage_critical: 3.7 # V

  # Just a marker to track, not a robot to connect to
  marker:
    connection: none
    motion_capture:
      enabled: true
      marker: default_single_marker
      dynamics: default

# global settings for all robots
all:
  # firmware parameters for all drones (use robot_types/type_name to set per type, or
  # robots/drone_name to set per drone)
  firmware_params:
    commander:
      enHighLevel: 1
    stabilizer:
      estimator: 2 # 1: complementary, 2: kalman
      controller: 6 # 1: PID, 2: mellinger 4: sjc 6: Lee 7: lee payload
      pAlphaV: 0.7
      pAlphaW: 0.7
    ctrlLee:
      Kpos_Px: 9.0 # def: 10.0
      Kpos_Py: 9.0 # def: 10.0
      Kpos_Pz: 9.0 # def: 10.0
      Kpos_Dx: 7.0  # def: 8.0
      Kpos_Dy: 7.0  # def: 8.0 
      Kpos_Dz: 7.0  # def: 8.0  
      Kpos_Ix: 5.0
      Kpos_Iy: 5.0
      Kpos_Iz: 8.0
      KR_x: 0.0055 #0.0055   # def: 0.005  
      KR_y: 0.0055 #0.0055  # def: 0.005
      KR_z: 0.01  #0.008   # def: 0.005
      Kw_x: 0.0013 #0.0013 # def: 0.0009
      Kw_y: 0.0013 #0.0013  # def: 0.0009
      Kw_z: 0.002  # def: 0.0012
      KI_x: 0.012 #0.009 #0.015
      KI_y: 0.018 #0.009 #0.015
      KI_z: 0.015 #0.009 #0.015
      mass: 0.0333
    ctrlLeeP:
      # P load
      Kpos_Px: 18.0
      Kpos_Py: 18.0
      Kpos_Pz: 18.0
      # D load
      Kpos_Dx: 16.0
      Kpos_Dy: 16.0
      Kpos_Dz: 16.0
      # I load
      Kpos_Ix: 5.0
      Kpos_Iy: 5.0
      Kpos_Iz: 11.0
      Kpos_I_limit: 100.0 #0.5

      # # P attitude Load: 
      # Kprot_Px: 0.0058
      # Kprot_Py: 0.0058
      # Kprot_Pz: 0.0058
      # #D attitude Load: 
      # Kprot_Dx: 0.0015
      # Kprot_Dy: 0.0015
      # Kprot_Dz: 0.0015
      # P cable
      Kqx: 19.0
      Kqy: 19.0
      Kqz: 19.0
      Kq_limit: 0.7
      # D cable
      Kwx: 14.0
      Kwy: 14.0
      Kwz: 14.0
      # I cable
      KqIx: 1.0
      KqIy: 1.0
      KqIz: 1.0

      # P angle
      KRx: 0.0076 #0.0055 #0.008
      KRy: 0.0076 #0.0055 #0.008
      KRz: 0.01         #0.01 #0.008
      # D angle
      Komx: 0.00115        #0.0013 #0.0017 #0.0013   #0.0017
      Komy: 0.00115        #0.0013 #0.0017 #0.0013   #0.0017
      Komz: 0.002          #0.0017
      # I angle
      KI_x: 0.03       #0.05 #0.01 #0.009 #0.015
      KI_y: 0.03        #0.05 #0.01 #0.009 #0.015
      KI_z: 0.03        #0.05 #0.01 #0.009 #0.015

      # mass: 0.034
      mass: 0.0356 # with LED ring, usd

      # payload properties
      # massP: 0.017
      # massP: 0.0054 # 2 UAV pointmass case
      massP: 0.01 # 2 UAV pointmass case
      # massP: 0.005 # 2 UAV pointmass case
      # form_ctrl: 3

      ap0id: 7
      ap0x: 0.0
      ap0y: 0.0
      ap0z: 0.0
      ap0l: 0.5 # manual cable length

      ap1id: 9
      ap1x: 0.0
      ap1y: 0.0
      ap1z: 0.0
      ap1l: 0.5 # manual cable length
      form_ctrl: 0
      Kpos_P_limit: 100.0 #0.5 #0.5
      Kpos_D_limit: 100.0 #0.1 #0.1
      radius: 0.15

      gen_hp: 1 # SVM-based hyperplane generation
      en_qdidot: 1 # enable qdidot computation
      # lambda_svm: 10000.0
      lambda_svm: 10.0

      lambda: 20.0

    # ring:
    #   effect: 7 # 6: double spinner, 7: solid color, 16: packetRate
    #   solidBlue: 255 # if set to solid color
    #   solidGreen: 0 # if set to solid color
    #   solidRed: 0 # if set to solid color
    #   headlightEnable: 0
    locSrv:
      extPosStdDev: 1e-3
      extQuatStdDev: 0.5e0 #0.5e0 #0.5e-1
    # kalman:
    #   resetEstimation: 1
    # cvmrs:
    #   exposure: 350 # int, > 200
    #   trigger: 1 # int
    # led:
    #   bitmask: 128s
  firmware_logging:
    enabled: false
    default_topics:
     # remove to disable default topic
      pose:
        frequency: 1 # Hz
    custom_topics:
      ctrlLeeP:
        frequency: 10 # Hz
        # vars: [ctrlLeeP.n1x, ctrlLeeP.n1y, ctrlLeeP.n1z, 
        #   ctrlLeeP.mu_refx, ctrlLeeP.mu_refy, ctrlLeeP.mu_refz]
        vars: [ctrlLeeP.n1x, ctrlLeeP.n1y, ctrlLeeP.n1z, ctrlLeeP.desVirtInpx,
          ctrlLeeP.desVirtInpy, ctrlLeeP.desVirtInpz]

      ctrlLeeP2:
        frequency: 10 # Hz
        vars: [ctrlLeeP.n2x, ctrlLeeP.n2y, ctrlLeeP.n2z, ctrlLeeP.Fdx, ctrlLeeP.Fdy,
          ctrlLeeP.Fdz]
      # payloadDbg:
      #  frequency: 10 # Hz
      #  vars: ["ctrlLeeP.Mdx", "ctrlLeeP.Mdy", "ctrlLeeP.Mdz"]
      #   #  vars: ["stateEstimate.pwx", "stateEstimate.pwy", "stateEstimate.pwz"]
      # #  vars: ["ctrlLeeP.profQP"]

      # setpoint:
      #  frequency: 100 # Hz
      #  vars: ["ctrltarget.x", "ctrltarget.y", "ctrltarget.z"]
