# named list of all robots
robots:
  cf10:
    enabled: true
    uri: radio://0/80/2M/E7E7E7E70A
    initial_position: [1.0, -1.0, 0.0]
    # initial_position: [0.0, 0.5, 0.0]
    type: cf21_betafpv # see robot_types
    firmware_params:
      ring:
        solidBlue: 255 # if set to solid color
        solidGreen: 0 # if set to solid color
        solidRed: 0 # if set to solid color

  cf11:
    enabled: true
    uri: radio://0/80/2M/E7E7E7E70B
    initial_position: [0.0, -1.0, 0.0]
    # initial_position: [0.0, -0.5, 0.0]
    type: cf21_betafpv # see robot_types
    firmware_params:
      ring:
        solidBlue: 0 # if set to solid color
        solidGreen: 0 # if set to solid color
        solidRed: 255 # if set to solid color

  payload3:
      enabled: true
      initial_position: [0.5, -1.0, 0.0]
      # initial_position: [0.0, 0.0, 0.0]
      type: mocap_rigidbody  # see robot_types
      id: 255

# Definition of the various robot types
robot_types:
  cf21_betafpv:
    motion_capture:
      enabled: true
      # only if enabled; see motion_capture.yaml
      marker: default_single_marker  #  default_single_marker
      dynamics: default
    big_quad: false
    battery:
      voltage_warning: 3.8  # V
      voltage_critical: 3.7 # V
    firmware_params:
      pwm:
        d00: 0.6034652836497831
        d10: 0.07227137807568539
        d01: -0.4832288487150109
        d20: -0.0009261372585960825
        d11: -0.0216219843334675

        e00: -12.564182528108777
        e10: 5.153254032178315
        e01: 34.40420347673405

  # Just a marker to track, not a robot to connect to
  marker:
      connection: none
      motion_capture:
          enabled: true
          marker: default_single_marker
          dynamics: default

  # An object tracked by the mocap, not a robot to connect to
  mocap_rigidbody:
      connection: none
      motion_capture:
          enabled: false

# global settings for all robots
all:
  # firmware parameters for all drones (use robot_types/type_name to set per type, or
  # robots/drone_name to set per drone)
  firmware_params:
    commander:
      enHighLevel: 1
    stabilizer:
      estimator: 2 # 1: complementary, 2: kalman
      controller: 6 # 1: PID, 2: mellinger 4: sjc 6: Lee 7: lee payload
      pAlphaV: 0.8
      pAlphaW: 0.5
    ctrlLee:
      Kpos_Px: 9.0 # def: 10.0
      Kpos_Py: 9.0 # def: 10.0
      Kpos_Pz: 9.0 # def: 10.0
      Kpos_Dx: 7.0  # def: 8.0
      Kpos_Dy: 7.0  # def: 8.0 
      Kpos_Dz: 7.0  # def: 8.0  
      Kpos_Ix: 5.0
      Kpos_Iy: 5.0
      Kpos_Iz: 8.0
      KR_x: 0.0055 #0.0055   # def: 0.005  
      KR_y: 0.0055 #0.0055  # def: 0.005
      KR_z: 0.01  #0.008   # def: 0.005
      Kw_x: 0.0013 #0.0013 # def: 0.0009
      Kw_y: 0.0013 #0.0013  # def: 0.0009
      Kw_z: 0.002  # def: 0.0012
      KI_x: 0.012 #0.009 #0.015
      KI_y: 0.018 #0.009 #0.015
      KI_z: 0.015 #0.009 #0.015
      mass: 0.0333
    ctrlLeeP:
      # P load
      Kpos_Px: 18.0
      Kpos_Py: 18.0
      Kpos_Pz: 18.0
      # D load
      Kpos_Dx: 16.0
      Kpos_Dy: 16.0
      Kpos_Dz: 16.0
      # I load
      Kpos_Ix: 5.0
      Kpos_Iy: 5.0
      Kpos_Iz: 11.0
      Kpos_I_limit: 100.0 #0.5

      # P attitude Load: 
      Kprot_Px: 0.008
      Kprot_Py: 0.008
      Kprot_Pz: 0.008
      #D attitude Load 
      Kprot_Dx: 0.002
      Kprot_Dy: 0.002
      Kprot_Dz: 0.002
      # I attitude Load
      Kprot_Ix: 0.0003
      Kprot_Iy: 0.0003
      Kprot_Iz: 0.0003

      # P cable
      Kqx: 12.0
      Kqy: 12.0
      Kqz: 12.0
      Kq_limit: 100.0 #0.7
      # D cable
      Kwx: 10.0
      Kwy: 10.0
      Kwz: 10.0
      # I cable
      KqIx: 0.5
      KqIy: 0.5
      KqIz: 0.5

      # integral gains Lee (30) -- (32)
      c_x: 100.0
      c_R: 100.0
      c_q: 100.0
      h_x0: 0.0 # payload position
      h_R0: 0.0 #0.00005 # payload attitude
      h_xi: 0.0 #0.00002 # cable

      # P angle
      KRx: 0.008
      KRy: 0.008
      KRz: 0.008
      # D angle
      en_num_w: 1
      Komx: 0.002
      Komy: 0.002
      Komz: 0.0015
      # I angle
      KI_x: 0.001
      KI_y: 0.001
      KI_z: 0.001

      # mass: 0.034
      mass: 0.0356 # with LED ring, usd

      en_qdidot: 0 # enable qdidot computation
      en_accrb: 1
      

      Kpos_P_limit: 100.0 #0.5 #0.5
      Kpos_D_limit: 100.0 #0.1 #0.1

      radius: 0.2
      gen_hp: 3 # SVM-based hyperplane generation
      lambda_svm: 100.0
      
      form_ctrl: 1
      lambda: 0.5
      # lambda_svm: 0.0
      # lambda: 1.0

      # payload properties (generated using gen_Pinv.py)
      Pinv000: 0.49999999999999956
      Pinv005: -7.1428571428571415
      Pinv011: 0.49999999999999983
      Pinv022: 0.49999999999999956
      Pinv023: 7.1428571428571415
      Pinv030: 0.5
      Pinv035: 7.1428571428571415
      Pinv041: 0.49999999999999983
      Pinv052: 0.5
      Pinv053: -7.1428571428571415
      Pinv0id1: 10
      Pinv0id2: 11
      ap0id: 10
      ap0l: 0.48
      ap0x: 0.0
      ap0y: 0.07
      ap0z: 0.0
      ap1id: 11
      ap1l: 0.5
      ap1x: 0.0
      ap1y: -0.07
      ap1z: 0.0
      massP: 0.0082


    ring:
      effect: 7 # 6: double spinner, 7: solid color, 16: packetRate
    #   solidBlue: 255 # if set to solid color
    #   solidGreen: 0 # if set to solid color
    #   solidRed: 0 # if set to solid color
    #   headlightEnable: 0
    locSrv:
      extPosStdDev: 1e-3
      extQuatStdDev: 0.5e0 #0.5e0 #0.5e-1
    # kalman:
    #   resetEstimation: 1
    # cvmrs:
    #   exposure: 350 # int, > 200
    #   trigger: 1 # int
    # led:
    #   bitmask: 128s
  firmware_logging:
    enabled: false
    default_topics:
     # remove to disable default topic
      pose:
        frequency: 1 # Hz
    custom_topics:
      ctrlLeeP:
        frequency: 10 # Hz
        vars: ["ctrlLeeP.n1x", "ctrlLeeP.n1y", "ctrlLeeP.n1z", "ctrlLeeP.desVirtInpx", "ctrlLeeP.desVirtInpy", "ctrlLeeP.desVirtInpz"]
      ctrlLeeP2:
        frequency: 10 # Hz
        vars: ["ctrlLeeP.n2x", "ctrlLeeP.n2y", "ctrlLeeP.n2z", 'ctrlLeeP.Fdx', "ctrlLeeP.Fdy", "ctrlLeeP.Fdz"]
      payloadDbg:
        frequency: 1 # Hz
        vars: ['ctrlLeeP.Mdx', "ctrlLeeP.Mdy", "ctrlLeeP.Mdz"]
      #  vars: ["ctrlLeeP.profQP"]

      # setpoint:
      #  frequency: 100 # Hz
      #  vars: ["ctrltarget.x", "ctrltarget.y", "ctrltarget.z"]
